#ifndef FINITEELEMENTRENDERLAYER_GLOBAL_H
#define FINITEELEMENTRENDERLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FINITEELEMENTRENDERLAYER_LIBRARY)
#  define FINITEELEMENTRENDERLAYER_EXPORT Q_DECL_EXPORT
#else
#  define FINITEELEMENTRENDERLAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // FINITEELEMENTRENDERLAYER_GLOBAL_H
