#ifndef OPENGLWINDOWLAYER_GLOBAL_H
#define OPENGLWINDOWLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENGLWINDOWLAYER_LIBRARY)
#  define OPENGLWINDOWLAYER_EXPORT Q_DECL_EXPORT
#else
#  define OPENGLWINDOWLAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENGLWINDOWLAYER_GLOBAL_H
